name: template
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod: ^3.0.3
  google_fonts: ^6.3.2
  intl: ^0.20.2
  easy_localization: ^3.0.8

  # Firebase
  firebase_core: ^4.2.0
  firebase_crashlytics: ^5.0.3

  pedantic_mono: ^1.34.0
  http: ^1.5.0
  just_audio: ^0.10.5
  youtube_explode_dart: ^2.5.2
  share_plus: ^12.0.1
  marquee: ^2.3.0
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/translations/
    - assets/audio/
